<?php

// PHP
$GLOBALS['AUTOLOAD_PHP_FRAMEWORK'] = array();
$GLOBALS['AUTOLOAD_PHP_APPLICATION'] = array();

// Component
$GLOBALS['AUTOLOAD_COMPONENT'] = array();

// CSS
$GLOBALS['AUTOLOAD_CSS_FRAMEWORK'] = array();
$GLOBALS['AUTOLOAD_CSS_APPLICATION'] = array();
$GLOBALS['AUTOLOAD_CSS_EXTERNAL'] = array();

// JS
$GLOBALS['AUTOLOAD_JS_FRAMEWORK'] = array();
$GLOBALS['AUTOLOAD_JS_APPLICATION'] = array();
$GLOBALS['AUTOLOAD_JS_EXTERNAL'] = array();
