<?php
if (!defined('SERVER_ROOT')) {header('/error_404');
	exit ;
}

$GLOBALS['AUTOLOAD_PHP_FRAMEWORK'] = array();
$GLOBALS['AUTOLOAD_PHP_APPLICATION'] = array();

$GLOBALS['AUTOLOAD_CSS_FRAMEWORK'] = array();
$GLOBALS['AUTOLOAD_CSS_APPLICATION'] = array();

$GLOBALS['AUTOLOAD_JS_FRAMEWORK'] = array();
$GLOBALS['AUTOLOAD_JS_APPLICATION'] = array();
